name: Build and publish add-on

on:
  push:
    branches:
      - main
    paths:
      - "fava/**"
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64
          - amd64
          - armhf
          - armv7
          - i386

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target fava \
            --docker-hub ghcr.io/${{ github.repository_owner }}
